### PR TITLE
avoid log event duplication (fixes #4)

### LINKED ISSUE #4: log event duplication
`attach_event => "newest" `
in logstash-filter-transaction_time (1.0.7) results in 2 equal log events, which can not be distinguished. A new transaction_time event is generated with exactly the same fields as the old 'newest' event. There should be an option to **disable** the new event in this case (or it should be disabled in general if attach_event != None is used)

hint: same result when using `attach_event => "last" `

### PR DESCRIPTION
**Pull request by DirkRichter**

### CODE REVIEW

**Comment by DirkRichter** [comment]
ping

**Review by welleby — APPROVED** [review]

**Comment by welleby** [comment]
Thanks. Sorry for the late reply.

**Comment by DirkRichter** [comment]
what about a new release?

**Comment by welleby** [comment]
I no longer have this project included in my daily work and i dont have the development environment setup. I just hade another child so this is not a priority of mine in the spare time either. Would you care to push it yourself if i provide you with the API key for RubyGems?

**Comment by DirkRichter** [comment]
Hi Tommy,

no thanks. Thus it’s more important to focus to the regular logstash-elaped plugin for implementing support of multiple workers there.

Kind Regards
Dirk

Von: Tommy Welleby [mailto:notifications@github.com]
Gesendet: Freitag, 13. Dezember 2019 09:26
An: AddinITAB/logstash-filter-transaction_time <logstash-filter-transaction_time@noreply.github.com>
Cc: Dirk Richter <d.richter@cid.com>; Author <author@noreply.github.com>
Betreff: Re: [AddinITAB/logstash-filter-transaction_time] avoid log event duplication (fixes #4) (#5)


I no longer have this project included in my daily work and i dont have the development environment setup. I just hade another child so this is not a priority of mine in the spare time either. Would you care to push it yourself if i provide you with the API key for RubyGems?

**Pull request merged**
